version: 0.2
phases:
  install:
    commands:
      - echo "Installing lint/sast software..."
      - pip install -q cfn-lint ansible-core ansible-lint
      - wget -q https://github.com/Checkmarx/kics/releases/download/v1.3.2/kics_1.3.2_linux_x64.tar.gz
      - tar -xf kics_1.3.2_linux_x64.tar.gz
      - echo "LINT/SAST Dependencies installed"
  pre_build:
    commands:
      - echo "Linting cloudformation code..."
      - find -iwholename "./cloudformation/*.yml" -exec cfn-lint -t {} -b --ignore-checks W \;
      - echo "Linting ansible code..."
      - cd ./ansible
      - ansible-lint --profile min 
      - echo "Running SAST on both cloudformation and ansible..."
      - cd ..
      - ./kics scan -p ./  --ignore-on-exit all
      - echo 'Linting and SAST Passed!'
      