AWSTemplateFormatVersion: 2010-09-09
Resources:
  TekPossibleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.84.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: aws_iac_generated
          Value: cloudformation
        - Key: Name
          Value: TekPossibleVPC
  TekPossibleDevelopment:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref TekPossibleVPC
      CidrBlock: 10.84.68.0/24
      Tags:
        - Key: aws_iac_generated
          Value: cloudformation
        - Key: Name
          Value: TekPossibleDevelopmentSubnet
  TekPossibleTest:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref TekPossibleVPC
      CidrBlock: 10.84.84.0/24
      Tags:
        - Key: aws_iac_generated
          Value: cloudformation
        - Key: Name
          Value: TekPossibleTestSubnet
  TekPossibleProduction: # This is our only public subnet
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref TekPossibleVPC
      CidrBlock: 10.84.80.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws_iac_generated
          Value: cloudformation
        - Key: Name
          Value: TekPossibleProductionSubnet
  TekPossibleIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: TekPossibleIGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref TekPossibleVPC
      InternetGatewayId: !Ref TekPossibleIGW