# CloudFormation Resources Definition for TekPossible Defense Networks.
# Part 1: Development Network (Additional security besides that in the AMI will be enforced via ansible/puppet after cloud formation)
# Property of Griffin Kiesecker, grifkies@protonmail.com
# TekPossible Defense Networks is a project to showcase my skills, and is in no way a real defense contractor!

Resources:
  use2devrhel9:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: use2-tekp-dev-el9
      DisableApiTermination: true
      ImageId: ami-030878695a26b4560 # This is the AMI that I premade. Enventually we will run a pre-CloudFormation ansible playbook that will make this AMI for us...
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroupIds: !Ref use2devrhel9sg
      UserData: !Base64 |
        #!/bin/bash 
        echo 'L Bozo!' /usr/you_suck.txt
      Tags:
        - Key: infrastructure_as_code
          Value: aws-cloudformation
  use2tekpdevigw:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: infrastructure_as_code
          Value: aws-cloudformation
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: vpc-id
      InternetGatewayId: !Ref use2tekpdevigw
  use2devrhel9sg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: use2-tekpdev-el9sg
      GroupDescription: TEKP RHEL 9 Development Security Group
      VpcId: null
      SecurityGroupIngress:
        - !ref <ingress here>
      SecurityGroupEgress:
        - !ref <egress here>
      Tags:
        - Key: infrastructure_as_code
          Value: aws-cloudformation

